version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@10.1.1
  aws-cli: circleci/aws-cli@0.1.13
  mem: circleci/rememborb@0.0.1

executors:
  default:
    docker:
      - image: circleci/python:3.8

jobs:
  run_gatling_tests:
    executor: 
      name: hmpps/java_localstack_postgres
      jdk_tag: "21.0"
      localstack_tag: "3.0"
      postgres_tag: "14.12"
    parameters:
      perf_test_users:
        type: integer
        default: 1
      perf_test_duration:
        type: integer
        default: 1
    steps:
      - checkout
      - run:
          name: create username var
          command: |
            echo "export PP_USERNAME=$PREPROD_USERNAME" >> $BASH_ENV
      - mem/remember:
          env_var: PP_USERNAME
          value: "${PP_USERNAME}"
      - run:
          name: create password var
          command: |
            echo "export PP_PASSWORD=$PREPROD_PASSWORD" >> $BASH_ENV
      - mem/remember:
          env_var: PP_PASSWORD
          value: "${PP_PASSWORD}"
      - mem/recall:
          env_var: PP_USERNAME
      - mem/recall:
          env_var: PP_PASSWORD
      - run:
          name: Run Gatling Tests
          command: |
            ./gradlew gatlingRun --all -Dusername=${PP_USERNAME} -Dpassword=${PP_PASSWORD} -Denv=preprod -Dusers=<<parameters.perf_test_users>> -Dramp=<<parameters.perf_test_duration>>
      - store_artifacts:
          path: build/reports/gatling
          destination: gatling-tests

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - hmpps/helm_lint:
          name: helm_lint
          context:
            - hmpps-common-vars
      - hmpps/build_docker:
          name: build_docker
          context:
            - hmpps-common-vars
      - request-preprod-100-users-approval:
          type: approval
          requires:
            - helm_lint
            - build_docker
      - run_gatling_tests:
          name: run_perf_100_users
          requires:
            - request-preprod-100-users-approval
          context:
            - hmpps-common-vars
            - court-probation-live-preprod
          perf_test_users: 100
          perf_test_duration: 10

      - request-preprod-500-users-approval:
          type: approval
          requires:
            - helm_lint
            - build_docker
      - run_gatling_tests:
          name: run_perf_500_users
          requires:
            - request-preprod-500-users-approval
          context:
            - hmpps-common-vars
            - court-probation-live-preprod
          perf_test_users: 500
          perf_test_duration: 10

      - request-preprod-1000-users-approval:
          type: approval
          requires:
            - helm_lint
            - build_docker
      - run_gatling_tests:
          name: run_perf_1000_users
          requires:
            - request-preprod-1000-users-approval
          context:
            - hmpps-common-vars
            - court-probation-live-preprod
          perf_test_users: 1000
          perf_test_duration: 10

      - request-preprod-1500-users-approval:
          type: approval
          requires:
            - helm_lint
            - build_docker
      - run_gatling_tests:
          name: run_perf_1500_users
          requires:
            - request-preprod-1500-users-approval
          context:
            - hmpps-common-vars
            - court-probation-live-preprod
          perf_test_users: 1500
          perf_test_duration: 10