apiVersion: batch/v1
kind: Job
metadata:
  name: "prepare-a-case-gatling-performance-tests"
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - name: "prepare-a-case-gatling-performance-tests"
        image: "{{ .Values.image.repository }}:latest"
        command:
          - /app/run.sh
        env:
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: perf-test-data-s3-credentials
                key: bucket_name
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: performance-test-data-user-credentials
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: performance-test-data-user-credentials
                key: password
          - name: PERF_TEST_USERS
            value: "{{ .Values.PERF_TEST_USERS }}"
          - name: PERF_TEST_DURATION
            value: "{{ .Values.PERF_TEST_DURATION }}"
          - name: JAVA_OPTS
            value: "-Xmx2048m -Xms1024m"
        resources:
          limits:
            cpu: 5000m
            memory: 3000Mi
          requests:
            cpu: 5000m
            memory: 3000Mi
      restartPolicy: Never
      serviceAccountName: "court-case-service"
  backoffLimit: 1
